config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# User card
get 'user_card/:user_id', to: 'user_card#show'

# Local avatar and letter avatar
match 'my/avatar', :to => 'my#avatar', :via => [:get, :post]
match 'my/save_avatar/:id', :to => 'my#save_avatar', :via => [:get, :post]
match 'account/get_avatar/:id', :to => 'account#get_avatar', :constraints => {:id=>/\d+/}, :via => [:get, :post]
match 'users/save_avatar/:id', :to => 'users#save_avatar', :constraints => {:id=>/\d+/}, :via => [:get, :post]
match 'users/get_avatar/:id', :to => 'users#get_avatar', :constraints => {:id=>/\d+/}, :via => [:get, :post]

# Todo
patch 'my-space/todo/issue/:id/complete', to: 'todo#complete_issue', as: :todo_issue_complete
post 'my-space/todo/lists/:list_id/issues', to: 'todo#create_issue'


get 'my-space/todo', :to => 'todo#index'
patch '/my-space/todo/issue/:id/move', to: 'todo#move_issue'
patch '/my-space/todo/list/:id/reorder', to: 'todo#reorder_list'



get 'my-space/todo/configuration_required', :to => 'todo#configuration_required'
get 'my-space/todo/today', :to => 'todo#today'
post 'my-space/todo/create', :to => 'todo#create'
post 'my-space/todo/list/add', :to => 'todo#list_add'
post 'my-space/todo/display', :to => 'todo#change_display'
post 'my-space/todo/list/:list_id/issue/:issue_id/move/:position_id', :to => 'todo#move'
post 'my-space/todo/list/:id/move/:position_id', :to => 'todo#move_list'
post 'my-space/todo/:id/update', :to => 'todo#update'
post 'my-space/todo/:id/update_tags', :to => 'issue_tags#update'
put 'my-space/todo/checklists/:id/done/', :to => 'todo#checklist_done'
post 'my-space/todo/checklists/:id/move/:position', :to => 'todo#checklist_move'
delete 'my-space/todo/checklists/:id/remove/', :to => 'todo#checklist_remove'
post 'my-space/todo/:issue_id/checklists/', :to => 'todo#checklist_create'
delete 'my-space/todo/:id', :to => 'todo#destroy'
delete 'my-space/todo/list/:id', :to => 'todo#version_destroy'
get 'my-space/todo/column/card/:id', :to => 'todo#card'
get 'my-space/todo/synchronize', :to => 'todo#synchronize_todo'


# Inbox
# get '/my-space/inbox', :to => 'inbox#index'
# get '/my-space/inbox/favorite', :to => 'inbox#favorite'
# # get '/my-space/inbox/issue/:id', :to => 'inbox#issue'
# get '/my-space/inbox/:id', to: 'inbox#show', as: 'inbox_issue'
scope path: 'my-space', as: 'my_space' do
  resources :inbox, only: [:index, :show] do
    collection do
      get :watched
    end
    post 'add_note', on: :member
  end
  resources :todo, only: [:index] do
    collection do
      post :synchronize
    end
  end
  resources :todo_lists, only: [:new, :create, :edit, :update, :show, :destroy]
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
    belongs_to :project
    acts_as_list :column => 'positionlist', :scope => [:project_id]
    has_many :todolist_issues
    has_many :issues, through: :todolist_issues
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  self.main_menu = false
  before_action :find_user_project, :except => [:destroy]

  def new
    @todo_list = TodoList.new
    render layout: false
  end

  def create
    version = Version.new(project_id: @user_project.id, name: list_params[:name])
    if version.save
      list = TodoList.new(
        name: version.name,
        project_id: @user_project.id,
        version_project_id: version.id,
        type_list: 'list'
      )
      if list.save
        redirect_to my_space_todo_path()
      else
        render json: { error: list.errors.full_messages }, status: :unprocessable_entity
      end
    else
      render json: { error: version.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def edit
    @todo_list = TodoList.find_by_id(params[:id])
    render :layout => false
  end

  def update
    @todo_list = TodoList.find_by_id(params[:id])
    @version = Version.find_by_id(@todo_list.version_project_id)
    if @todo_list.update!(name: list_params[:name])
      @version.update!(name: list_params[:name])
      redirect_to my_space_todo_path()
    else
      redirect_to my_space_todo_path()
    end
  end

  def destroy
    @todo_list = TodoList.find_by_id(params[:id])
    return redirect_to my_space_todo_path, alert: 'Liste introuvable' unless @todo_list

    @version = Version.find_by_id(@todo_list.version_project_id)
    return redirect_to my_space_todo_path, alert: 'Version associée introuvable' unless @version

    fallback_version = find_fallback_version(@version)
    return redirect_to my_space_todo_path, alert: 'Aucune version de repli disponible' unless fallback_version

    fallback_list = TodoList.find_by(version_project_id: fallback_version.id)
    unless fallback_list
      # Si aucune todo_list pour la version fallback, on peut en créer une (optionnel)
      fallback_list = TodoList.create!(
        name: fallback_version.name,
        project_id: fallback_version.project_id,
        version_project_id: fallback_version.id,
        type_list: 'list'
      )
    end

    # Déplacer les issues dans la bonne version ET bonne todo_list
    @version.fixed_issues.each do |issue|
      issue.update!(fixed_version: fallback_version)

      # Trouver ou créer la liaison avec la fallback todo_list
      todo_link = TodolistIssue.find_or_initialize_by(issue_id: issue.id)
      todo_link.todo_list_id = fallback_list.id
      todo_link.save!
    end

    @version.destroy
    @todo_list.destroy

    redirect_to my_space_todo_path
  end



  private

  def find_user_project
    @user_project = Project.find(params[:project_id] || params[:id])
  end

  def list_params
    params.require(:todo_list).permit(:name)
  end

  def find_fallback_version(version)
    # 1. Tenter de trouver la version par défaut du projet utilisateur
    user_project = Project.find_by_id(version.project.id)
    return user_project.default_version if user_project&.default_version && user_project.default_version != version

    # 2. Sinon, prendre une autre version du même projet
    version.project.versions.where.not(id: version.id).first
  end

end

app/views/todo_lists/edit.html.erb
<div data-todo-target="modal" class="fixed inset-0 z-50 bg-black/50 flex items-center justify-center">
  <div data-todo-target="modalBody" class="bg-white dark:bg-dark-700  p-4 rounded-lg shadow-xl w-full max-w-lg">
    <h2 class="text-lg font-semibold mb-4"><%= l(:label_list_edit) %></h2>
    <%= form_with model: @todo_list, url: my_space_todo_list_path(@todo_list), method: :patch, local: true do |f| %>
      <div class="mb-4">
        <%= hidden_field_tag :project_id, @user_project.id %>
        <%= f.label :title, l(:label_list_name), class: "block text-sm font-medium" %>
        <%= f.text_field :name, class: "mt-1 block w-full border rounded" %>
      </div>
      <div class="flex justify-end space-x-2">
        <button type="button" data-action="click->todo#hide" class="text-gray-600 dark:text-gray-200  hover:underline"><%= l(:label_list_cancel) %></button>
        <%= f.submit l(:label_list_save), class: "bg-blue-700 text-white px-4 py-2 rounded hover:bg-blue-800" %>
      </div>
    <% end %>
  </div>
</div>

app/views/todo_lists/new.html.erb
<div data-todo-target="modal" class="fixed inset-0 z-50 bg-black/50 flex items-center justify-center">
  <div data-todo-target="modalBody" class="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-xl w-full max-w-lg">
    <h2 class="text-lg font-semibold mb-4"><%= l(:label_list_new) %></h2>
    <%= form_with model: @todo_list, url: my_space_todo_lists_path, local: true do |f| %>
      <div class="mb-4">
        <%= hidden_field_tag :project_id, @user_project.id %>
        <%= f.label :title, l(:label_list_name), class: "block text-sm font-medium" %>
        <%= f.text_field :name, class: "mt-1 block w-full border rounded" %>
      </div>
      <div class="flex justify-end space-x-2">
        <button type="button" data-action="click->todo#hide" class="text-gray-600 dark:text-gray-200 hover:underline"><%= l(:label_list_cancel) %></button>
        <%= f.submit l(:label_list_create), class: "bg-blue-700 text-white px-4 py-2 rounded hover:bg-blue-800" %>
      </div>
    <% end %>
  </div>
</div>