config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# User card
get 'user_card/:user_id', to: 'user_card#show'

# Local avatar and letter avatar
match 'my/avatar', :to => 'my#avatar', :via => [:get, :post]
match 'my/save_avatar/:id', :to => 'my#save_avatar', :via => [:get, :post]
match 'account/get_avatar/:id', :to => 'account#get_avatar', :constraints => {:id=>/\d+/}, :via => [:get, :post]
match 'users/save_avatar/:id', :to => 'users#save_avatar', :constraints => {:id=>/\d+/}, :via => [:get, :post]
match 'users/get_avatar/:id', :to => 'users#get_avatar', :constraints => {:id=>/\d+/}, :via => [:get, :post]

# Todo
patch 'my-space/todo/issue/:id/complete', to: 'todo#complete_issue', as: :todo_issue_complete
post 'my-space/todo/lists/:list_id/issues', to: 'todo#create_issue'


get 'my-space/todo', :to => 'todo#index'
patch '/my-space/todo/issue/:id/move', to: 'todo#move_issue'
patch '/my-space/todo/list/:id/reorder', to: 'todo#reorder_list'



get 'my-space/todo/configuration_required', :to => 'todo#configuration_required'
get 'my-space/todo/today', :to => 'todo#today'
post 'my-space/todo/create', :to => 'todo#create'
post 'my-space/todo/list/add', :to => 'todo#list_add'
post 'my-space/todo/display', :to => 'todo#change_display'
post 'my-space/todo/list/:list_id/issue/:issue_id/move/:position_id', :to => 'todo#move'
post 'my-space/todo/list/:id/move/:position_id', :to => 'todo#move_list'
post 'my-space/todo/:id/update', :to => 'todo#update'
post 'my-space/todo/:id/update_tags', :to => 'issue_tags#update'
put 'my-space/todo/checklists/:id/done/', :to => 'todo#checklist_done'
post 'my-space/todo/checklists/:id/move/:position', :to => 'todo#checklist_move'
delete 'my-space/todo/checklists/:id/remove/', :to => 'todo#checklist_remove'
post 'my-space/todo/:issue_id/checklists/', :to => 'todo#checklist_create'
delete 'my-space/todo/:id', :to => 'todo#destroy'
delete 'my-space/todo/list/:id', :to => 'todo#version_destroy'
get 'my-space/todo/column/card/:id', :to => 'todo#card'
get 'my-space/todo/synchronize', :to => 'todo#synchronize_todo'


# Inbox
# get '/my-space/inbox', :to => 'inbox#index'
# get '/my-space/inbox/favorite', :to => 'inbox#favorite'
# # get '/my-space/inbox/issue/:id', :to => 'inbox#issue'
# get '/my-space/inbox/:id', to: 'inbox#show', as: 'inbox_issue'
scope path: 'my-space', as: 'my_space' do
  resources :inbox, only: [:index, :show] do
    collection do
      get :watched
    end
    post 'add_note', on: :member
  end
  resources :todo, only: [:index] do
    collection do
      post :synchronize
    end
  end
  resources :todo_lists, only: [:new, :create, :edit, :update, :show, :destroy]
end

app/controllers/inbox_controller.rb
class InboxController < ApplicationController
  helper :all
  before_action :find_issues_counts
  self.main_menu = false
  layout 'inbox'



  # INBOX
  def index

    @issues = Issue.visible.open
              .assigned_to(User.current)
              .order(Arel.sql("COALESCE(issues.updated_on, issues.created_on) DESC"))
    @first_issue = @issues.first
    if @first_issue
      @journals = @first_issue.visible_journals_with_index
      @journals.reverse! if User.current.wants_comments_in_reverse_order?
      @relations = @first_issue.relations.select {|r| r.other_issue(@first_issue)&.visible?}
      @relation ||= IssueRelation.new
    end
  end

  def show
    @issue = Issue.find(params[:id])
    @journals = @issue.visible_journals_with_index
    @journals.reverse! if User.current.wants_comments_in_reverse_order?
    @relations = @issue.relations.select {|r| r.other_issue(@issue)&.visible?}
    @relation ||= IssueRelation.new
    respond_to do |format|
      format.html do
        # Appel normal (visite directe) → affiche toute la vue avec les 3 colonnes
        @issues = Issue.visible.open
                  .assigned_to(User.current)
                  .order(Arel.sql("COALESCE(issues.updated_on, issues.created_on) DESC"))
        @first_issue = @issue

        render :index
      end

      format.js do
        # Appel AJAX → ne rend que le détail
        render partial: "inbox/detail", locals: { issue: @issue, journals: @journals }
      end

      # fallback (au cas où)
      format.any { head :not_acceptable }
    end
  end


  def add_note
    @issue = Issue.find(params[:id])
    # @project = @issue.project   <-- retirer cette ligne

    unless @issue.notes_addable?
      render plain: "Not allowed", status: :forbidden
      return
    end

    journal = @issue.init_journal(User.current)
    journal.notes = params[:notes]
    journal.private_notes = params[:private_notes] == "1"

    if @issue.save
      flash[:notice] = l(:notice_successful_update)
    else
      flash[:error] = l(:error_can_not_save_issue)
    end

    redirect_to my_space_inbox_path(id: @issue.id, anchor: "issue-#{@issue.id}")
  end


  def watched
    @issues_watched = Issue.visible.open
                      .joins(:watchers)
                      .where(watchers: { user_id: User.current.id })
                      .distinct
                      .order(Arel.sql("COALESCE(issues.updated_on, issues.created_on) DESC"))

    @first_issue = @issues_watched.first

  end


  private

  def find_issues_counts
    @issues_count = Issue.visible.open.where(assigned_to_id: User.current.id).count
    @issues_watched_count = Issue.visible.open.joins(:watchers)
                                 .where(watchers: { user_id: User.current.id }).count
  end


  def issue_params
      params.require(:issue).permit(
          :id, :notes
      )
  end
end

app/helpers/inbox_helper.rb
module InboxHelper
    include ApplicationHelper
    include ActionView::Helpers::TagHelper   
    include ERB::Util 
    include CustomFieldsHelper
    
    def show_detail_inbox(detail, no_html=false, options={})
        multiple = false
        show_diff = false
        no_details = false

        case detail.property
        when 'attr'
            field = detail.prop_key.to_s.gsub(/\_id$/, "")
            label = l(("field_" + field).to_sym)
        case detail.prop_key
        when 'due_date', 'start_date'
            value = format_date(detail.value.to_date) if detail.value
            old_value = format_date(detail.old_value.to_date) if detail.old_value

        when 'project_id', 'status_id', 'tracker_id', 'assigned_to_id',
                'priority_id', 'category_id', 'fixed_version_id'
            value = find_name_by_reflection(field, detail.value)
            old_value = find_name_by_reflection(field, detail.old_value)

        when 'estimated_hours'
            value = l_hours_short(detail.value.to_f) unless detail.value.blank?
            old_value = l_hours_short(detail.old_value.to_f) unless detail.old_value.blank?

        when 'parent_id'
            label = l(:field_parent_issue)
            value = "##{detail.value}" unless detail.value.blank?
            old_value = "##{detail.old_value}" unless detail.old_value.blank?

        when 'is_private'
            value = l(detail.value == "0" ? :general_text_No : :general_text_Yes) unless detail.value.blank?
            old_value = l(detail.old_value == "0" ? :general_text_No : :general_text_Yes) unless detail.old_value.blank?

        when 'description'
            show_diff = true
        end
        when 'cf'
            custom_field = detail.custom_field
            if custom_field
                label = custom_field.name
                if custom_field.format.class.change_no_details
                    no_details = true
                elsif custom_field.format.class.change_as_diff
                    show_diff = true
                else
                    multiple = custom_field.multiple?
                    value = format_value(detail.value, custom_field) if detail.value
                    old_value = format_value(detail.old_value, custom_field) if detail.old_value
                end
            end
        when 'attachment'
            label = l(:label_attachment)
        when 'relation'
            if detail.value && !detail.old_value
                rel_issue = Issue.visible.find_by_id(detail.value)
                value =
                if rel_issue.nil?
                    "#{l(:label_issue)} ##{detail.value}"
                else
                    (no_html ? rel_issue : link_to_issue(rel_issue, :only_path => options[:only_path]))
                end
            elsif detail.old_value && !detail.value
                rel_issue = Issue.visible.find_by_id(detail.old_value)
                old_value =
                if rel_issue.nil?
                    "#{l(:label_issue)} ##{detail.old_value}"
                else
                    (no_html ? rel_issue : link_to_issue(rel_issue, :only_path => options[:only_path]))
                end
            end
            relation_type = IssueRelation::TYPES[detail.prop_key]
            label = l(relation_type[:name]) if relation_type
        end
        call_hook(:helper_issues_show_detail_after_setting,
                {:detail => detail, :label => label, :value => value, :old_value => old_value })

        label ||= detail.prop_key
        value ||= detail.value
        old_value ||= detail.old_value

        unless no_html
        label = content_tag('strong', label)
        old_value = content_tag("i", h(old_value)) if detail.old_value
        if detail.old_value && detail.value.blank? && detail.property != 'relation'
            old_value = content_tag("del", old_value)
        end
        if detail.property == 'attachment' && value.present? &&
            atta = detail.journal.journalized.attachments.detect {|a| a.id == detail.prop_key.to_i}
            # Link to the attachment if it has not been removed
            value = link_to_attachment(atta, only_path: options[:only_path])
            if options[:only_path] != false
            value += ' '
            value += link_to_attachment atta, class: 'icon-only icon-download', title: l(:button_download), download: true
            end
        else
            value = content_tag("i", h(value)) if value
        end
    end

    if no_details
      s = l(:text_journal_changed_no_detail, :label => label).html_safe
    elsif show_diff
      s = l(:text_journal_changed_no_detail, :label => label)
      unless no_html
        diff_link =
          link_to(
            'diff',
            diff_journal_url(detail.journal_id, :detail_id => detail.id,
                             :only_path => options[:only_path]),
            :title => l(:label_view_diff))
        s << " (#{diff_link})"
      end
      s.html_safe
    elsif detail.value.present?
      case detail.property
      when 'attr', 'cf'
        if detail.old_value.present?
          l(:text_journal_changed, :label => label, :old => old_value, :new => value).html_safe
        elsif multiple
          l(:text_journal_added, :label => label, :value => value).html_safe
        else
          l(:text_journal_set_to, :label => label, :value => value).html_safe
        end
      when 'attachment', 'relation'
        l(:text_journal_added, :label => label, :value => value).html_safe
      end
    else
      l(:text_journal_deleted, :label => label, :old => old_value).html_safe
    end
  end

    def details_to_strings_inbox(details, no_html=false, options={})
        options[:only_path] = !(options[:only_path] == false)
        strings = []
        values_by_field = {}
        details.each do |detail|
            if detail.property == 'cf'
                field = detail.custom_field
                if field && field.multiple?
                    values_by_field[field] ||= {:added => [], :deleted => []}
                    if detail.old_value
                        values_by_field[field][:deleted] << detail.old_value
                    end
                    if detail.value
                        values_by_field[field][:added] << detail.value
                    end
                    next
                end
            end
            strings << show_detail_inbox(detail, no_html, options)
        end
        if values_by_field.present?
            values_by_field.each do |field, changes|
                if changes[:added].any?
                    detail = MultipleValuesDetail.new('cf', field.id.to_s, field)
                    detail.value = changes[:added]
                    strings << show_detail_inbox(detail, no_html, options)
                end
                if changes[:deleted].any?
                    detail = MultipleValuesDetail.new('cf', field.id.to_s, field)
                    detail.old_value = changes[:deleted]
                    strings << show_detail_inbox(detail, no_html, options)
                end
            end
        end
        strings
    end
end

app/views/inbox/_column_left.html.erb
<!-- Colonne gauche -->
<div class="flex-none basis-auto md:basis-[280px] shrink-0 p-4 shadow-xs border-r border-gray-100 dark:border-gray-500 dark:bg-gray-800 mt-4">
  <ul class="space-y-2">
    <li class="rounded p-2 hover:bg-gray-100 dark:hover:bg-gray-700 <%= 'font-semibold text-blue-600! dark:text-blue-300! bg-gray-100 dark:bg-gray-700' if (current_page?(my_space_inbox_index_path) || (current_page?(my_space_inbox_path())  rescue false) ) %>">
      <%= link_to my_space_inbox_index_path, class: 'flex text-gray-900! dark:text-gray-300!' do %>
        <%= sprite_icon('inbox', plugin: 'redmine_asap_user_features', css_class: 'stroke-gray-900! dark:stroke-gray-300!') %>
        <span class="ml-2"><%= l(:label_menu_asap_inbox) %>
        (<%= @issues_count %>)</span>
      <% end %>
    </li>
    <li class="rounded p-2 hover:bg-gray-100 dark:hover:bg-gray-700 <%= 'font-semibold text-blue-600! dark:text-blue-300! bg-gray-100 dark:bg-gray-700' if current_page?(watched_my_space_inbox_index_path) %>">
      <%= link_to watched_my_space_inbox_index_path, class: 'flex text-gray-900! dark:text-gray-300!' do %>
        <%= sprite_icon('fav', css_class: 'stroke-gray-900! dark:stroke-gray-300!') %>
        <span class="ml-2"><%= l(:label_menu_asap_watched_issues) %>
        (<%= @issues_watched_count %>)</span>
      <% end %>
    </li>
  </ul>
</div>

app/views/inbox/_column_middle.html.erb
<!-- Colonne du milieu : liste -->
<div class="flex-none basis-[350px] shrink-0  overflow-auto shadow-xs border-r border-gray-100 dark:border-gray-700" data-inbox-target="list">
  <%= render partial: "list", locals: { issues: issues } %>
</div>

app/views/inbox/_column_right.html.erb
<div class="flex-1 w-full h-full sm:overflow-y-auto p-4" data-inbox-target="detail">
  <% if @first_issue %>
    <%= render partial: "detail", locals: { issue: @first_issue, journals: @journals } %>
  <% else %>
    <p>Aucune demande assignée</p>
  <% end %>
</div>

app/views/inbox/_detail.html.erb
<% @issue ||= defined?(issue) ? issue : nil %>
<% @journals ||= defined?(journals) ? journals : [] %>

<header class="w-full relative bg-white dark:bg-gray-800 shadow px-8 py-4 flex items-center mb-2">
  <h3 class="font-medium py-2 my-0! text-sm flex">
    <strong>#<%= @issue.id %></strong> - <%= @issue.subject %>
  </h3>

  <div id="issue-menu" class="ml-auto!">

    <%= actions_dropdown do %>
      <%= link_to sprite_icon('edit', l(:button_edit)), edit_issue_path(@issue),
      :onclick => 'showAndScrollTo("update", "issue_notes"); return false;',
      :class => 'icon icon-edit ', :accesskey => accesskey(:edit) if @issue.editable? %>

      <%= watcher_link(@issue, User.current) %>

      <%= copy_object_url_link(issue_url(@issue, only_path: false)) %>


      <%= link_to sprite_icon('time-add', l(:button_log_time)), new_issue_time_entry_path(@issue),
                  :class => 'icon icon-time-add ' if User.current.allowed_to?(:log_time, @project) %>
      <%= link_to sprite_icon('copy', l(:button_copy)), project_copy_issue_path(@project, @issue),
                  :class => 'icon icon-copy ' if User.current.allowed_to?(:copy_issues, @project) && Issue.allowed_target_projects.any? %>
                  <%= link_to sprite_icon('del', l(:button_delete_object, object_name: l(:label_issue)).capitalize), issue_path(@issue),
                  :data => {:confirm => issues_destroy_confirmation_message(@issue)},
                  :method => :delete, :class => 'icon icon-del ' if @issue.deletable? %>
    <% end %>
    </div>

</header>

<section class="w-full bg-white dark:bg-gray-800 shadow px-8 py-8 flex flex-col">
  <div class="flex items-center mb-4">
    <%= author_avatar(@issue.author, :size => "30") %>
    <div class="ml-3 flex flex-col">
      <div><%= @issue.author %></div>
    </div>
    <div class="ml-auto"><%= link_to_project(@issue.project) %></div>
  </div>
  <div id="attribute" class="bg-gray-50 dark:bg-gray-700 rounded p-8">
    <%= issue_fields_rows do |rows|
      rows.left l(:field_status), @issue.status.name, :class => 'status'

      unless @issue.disabled_core_fields.include?('priority_id')
        rows.left l(:field_priority), @issue.priority.name, :class => 'priority'
      end
      unless @issue.disabled_core_fields.include?('assigned_to_id')
        rows.left l(:field_assigned_to), (@issue.assigned_to ? link_to_principal(@issue.assigned_to) : "-"), :class => 'assigned-to'
      end
      unless @issue.disabled_core_fields.include?('category_id') || (@issue.category.nil? && @issue.project.issue_categories.none?)
        rows.left l(:field_category), (@issue.category ? @issue.category.name : "-"), :class => 'category'
      end
      unless @issue.disabled_core_fields.include?('fixed_version_id') || (@issue.fixed_version.nil? && @issue.assignable_versions.none?)
        rows.left l(:field_fixed_version), (@issue.fixed_version ? link_to_version(@issue.fixed_version) : "-"), :class => 'fixed-version'
      end

      unless @issue.disabled_core_fields.include?('start_date')
        rows.right l(:field_start_date), format_date(@issue.start_date), :class => 'start-date'
      end
      unless @issue.disabled_core_fields.include?('due_date')
        rows.right l(:field_due_date), issue_due_date_details(@issue), :class => 'due-date'
      end
      unless @issue.disabled_core_fields.include?('done_ratio')
        rows.right l(:field_done_ratio), progress_bar(@issue.done_ratio, :legend => "#{@issue.done_ratio}%"), :class => 'progress'
      end
      unless @issue.disabled_core_fields.include?('estimated_hours')
        rows.right l(:field_estimated_hours), issue_estimated_hours_details(@issue), :class => 'estimated-hours'
      end
      if User.current.allowed_to?(:view_time_entries, @project) && @issue.total_spent_hours > 0
        rows.right l(:label_spent_time), issue_spent_hours_details(@issue), :class => 'spent-time'
      end
    end %>
    <%= render_half_width_custom_fields_rows(@issue) %>
  </div>

</section>

<section class="w-full bg-white dark:bg-gray-800 shadow px-8 py-2 flex no-wrap flex-col">
  <% if @issue.description? %>
  <div id="issue_description_wiki" class="wiki py-4 mb-6 text-wrap">
    <%= textilizable @issue, :description, :attachments => @issue.attachments %>
    </div>
  <% end %>

  <% if @issue.attachments.any? %>
    <div id="issue-attachments" class="border-t border-gray-100 dark:border-gray-600 pt-6 mb-6">
      <p class="pb-4"><strong><%=l(:label_attachment_plural)%></strong></p>
      <%= link_to_attachments @issue, :thumbnails => true %>
    </div>
  <% end %>


</section>


<% if !@issue.leaf? || User.current.allowed_to?(:manage_subtasks, @project) || @relations.present? || User.current.allowed_to?(:manage_issue_relations, @project)  %>
<section class="w-full bg-white dark:bg-gray-800 shadow px-8 py-8 flex no-wrap flex-col mt-2">
  <% if !@issue.leaf? || User.current.allowed_to?(:manage_subtasks, @project) %>

  <div id="issue_tree">
  <%= render :partial => 'issues/subtasks' %>
  </div>
  <% end %>

  <% if @relations.present? || User.current.allowed_to?(:manage_issue_relations, @project) %>

  <div id="relations">
  <%= render :partial => 'issues/relations' %>
  </div>
  <% end %>
</section>
<% end %>

<section class="w-full bg-white dark:bg-gray-800 shadow px-8 py-8 flex no-wrap flex-col mt-2">
  <div id="history">
    <%= render_tabs issue_history_tabs, issue_history_default_tab %>
  </div>

  <% if @issue.notes_addable? %>
    <%= form_with url: add_note_my_space_inbox_path(@issue.id), method: :post, multipart: true, local: true do |f| %>
          <fieldset id="add_notes" class="border-0!"><legend><%= l(:field_notes) %></legend>
          <%= f.text_area :notes, :cols => 60, :rows => 10, :class => 'wiki-edit',
                :data => {
                    :auto_complete => true
                },
                :no_label => true %>
          <%= wikitoolbar_for 'issue_notes', preview_issue_path(:project_id => @project ||= @issue.project , :issue_id => @issue) %>

          <% if @issue.safe_attribute? 'private_notes' %>
          <div class="flex items-center space-x-2 my-1">
            <%= f.check_box :private_notes, :no_label => true %> <label for="issue_private_notes"><%= l(:field_private_notes) %></label>
          </div>
          <% end %>

          <%= call_hook(:view_issues_edit_notes_bottom, { :issue => @issue, :notes => @notes, :form => f }) %>
          </fieldset>

          <%= f.hidden_field :lock_version %>
        <%= hidden_field_tag 'last_journal_id', params[:last_journal_id] || @issue.last_journal_id %>
        <div class="flex justify-end items-center space-x-2">

          <%= link_to(
              l(:button_cancel), issue_path(id: @issue.id),
              :onclick => params[:action] == 'show' ? "$('#update').hide(); return false;" : ''
            ) %>

            <%= submit_tag l(:button_submit) %>
        </div>


      <% end %>
    <% end %>

</section>

app/views/inbox/_list.html.erb
<% if issues %>
  <ul class="mt-4">
    <% issues.each do |issue| %>
      <%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do -%>
      <%= hidden_field_tag 'ids[]', issue.id %>
        <li id="issue-<%= issue.id %>" class="bg-white dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 p-4 cursor-pointer flex  shadow border-b border-gray-100 dark:border-gray-600 hascontextmenu  "
            data-action="click->inbox#show"
            data-inbox-id-param="<%= issue.id %>"
            data-inbox-target="item">
            <div class="mr-2">
              <%= author_avatar(issue.author, :size => "30") %>
            </div>
            <div class="flex flex-col">
              <div class="mb-2">
                <span class="text-gray-700 dark:text-gray-300"><%= issue.author %></span>
                <div class="ml-auto text-gray-400 dark:text-gray-500 text-xs">
                  <% if issue.created_on != issue.updated_on %>
                    <%= l(:label_updated_time, time_tag(issue.updated_on)).html_safe %>
                  <% else %>
                    <%= l(:label_created_on) %>&nbsp;<%= time_tag(issue.created_on) %>
                  <% end %>
                </div>
              </div>
              <div>
                <strong>#<%= issue.id %></strong> - <%= issue.subject %>
              </div>
            </div>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>
<%= context_menu %>

app/views/inbox/index.html.erb
<div class="flex h-[calc(100vh-6rem)]  overflow-auto">
  <%= render "shared/sidebar" %>

  <div data-controller="inbox" class="flex flex-col md:flex-row flex-1 h-full ml-14">
    <%= render :partial => "column_left", locals: {issues: @issues, issues_watched_count: @issues_watched_count} %>
    <%= render :partial => "column_middle", locals: {issues: @issues} %>
    <%= render "column_right" %>
  </div>
</div>

app/views/inbox/watched.html.erb
<div class="flex h-[calc(100vh-6rem)]  overflow-auto">
  <%= render "shared/sidebar" %>

  <div data-controller="inbox" class="flex flex-1 h-full ml-14">
    <%= render :partial => "column_left", locals: {issues: nil, issues_watched: @issues_watched} %>
    <%= render :partial => "column_middle", locals: {issues: @issues_watched} %>
    <%= render "column_right" %>
  </div>
</div>