config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# User card
get 'user_card/:user_id', to: 'user_card#show'

# Local avatar and letter avatar
match 'my/avatar', :to => 'my#avatar', :via => [:get, :post]
match 'my/save_avatar/:id', :to => 'my#save_avatar', :via => [:get, :post]
match 'account/get_avatar/:id', :to => 'account#get_avatar', :constraints => {:id=>/\d+/}, :via => [:get, :post]
match 'users/save_avatar/:id', :to => 'users#save_avatar', :constraints => {:id=>/\d+/}, :via => [:get, :post]
match 'users/get_avatar/:id', :to => 'users#get_avatar', :constraints => {:id=>/\d+/}, :via => [:get, :post]

# Todo
patch 'my-space/todo/issue/:id/complete', to: 'todo#complete_issue', as: :todo_issue_complete
post 'my-space/todo/lists/:list_id/issues', to: 'todo#create_issue'


get 'my-space/todo', :to => 'todo#index'
patch '/my-space/todo/issue/:id/move', to: 'todo#move_issue'
patch '/my-space/todo/list/:id/reorder', to: 'todo#reorder_list'



get 'my-space/todo/configuration_required', :to => 'todo#configuration_required'
get 'my-space/todo/today', :to => 'todo#today'
post 'my-space/todo/create', :to => 'todo#create'
post 'my-space/todo/list/add', :to => 'todo#list_add'
post 'my-space/todo/display', :to => 'todo#change_display'
post 'my-space/todo/list/:list_id/issue/:issue_id/move/:position_id', :to => 'todo#move'
post 'my-space/todo/list/:id/move/:position_id', :to => 'todo#move_list'
post 'my-space/todo/:id/update', :to => 'todo#update'
post 'my-space/todo/:id/update_tags', :to => 'issue_tags#update'
put 'my-space/todo/checklists/:id/done/', :to => 'todo#checklist_done'
post 'my-space/todo/checklists/:id/move/:position', :to => 'todo#checklist_move'
delete 'my-space/todo/checklists/:id/remove/', :to => 'todo#checklist_remove'
post 'my-space/todo/:issue_id/checklists/', :to => 'todo#checklist_create'
delete 'my-space/todo/:id', :to => 'todo#destroy'
delete 'my-space/todo/list/:id', :to => 'todo#version_destroy'
get 'my-space/todo/column/card/:id', :to => 'todo#card'
get 'my-space/todo/synchronize', :to => 'todo#synchronize_todo'


# Inbox
# get '/my-space/inbox', :to => 'inbox#index'
# get '/my-space/inbox/favorite', :to => 'inbox#favorite'
# # get '/my-space/inbox/issue/:id', :to => 'inbox#issue'
# get '/my-space/inbox/:id', to: 'inbox#show', as: 'inbox_issue'
scope path: 'my-space', as: 'my_space' do
  resources :inbox, only: [:index, :show] do
    collection do
      get :watched
    end
    post 'add_note', on: :member
  end
  resources :todo, only: [:index] do
    collection do
      post :synchronize
    end
  end
  resources :todo_lists, only: [:new, :create, :edit, :update, :show, :destroy]
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
  self.main_menu = false

  before_action :find_project, except: [:configuration_required]
  before_action :find_todo_list, only: [:create_issue]

  def index
    @todo_lists = TodoList.where(project_id: @user_project.id, type_list: 'list')
                          .order(positionlist: :asc)

    # Si aucune liste → on synchronise, et on récupère la liste générée
    if @todo_lists.empty?
      @todo_lists = synchronize_todo_lists_with_project_versions
    end

    issues_closed_status = IssueStatus.where(is_closed: true).first
    priorities = IssuePriority.active

    # Affichage colonne → défaut
    display_todo = User.current.pref[:todo_display]
    if display_todo.blank?
      User.current.pref[:todo_display] = 'columns'
      User.current.pref.save!
      display_todo = 'columns'
    end

    # Garde uniquement les issues ouvertes
    @todo_lists = get_only_opened_issues_from_todo_lists(@todo_lists)
  end

  def complete_issue
    @issue = Issue.find(params[:id])
    closed_status = IssueStatus.where(is_closed: true).first

    @issue.update!(status: closed_status)

    respond_to do |format|
      format.js
      format.html { redirect_back fallback_location: root_path }
    end
  end

  def create_issue
    list = TodoList.find_by(id: params[:list_id])
    return render json: { error: 'Liste inconnue' }, status: :not_found unless list

    tracker = list.project.trackers.first
    return render json: { error: 'Aucun tracker actif pour ce projet' }, status: :unprocessable_entity unless tracker

    status = IssueStatus.where(is_closed: false).first
    return render json: { error: 'Aucun statut ouvert disponible' }, status: :unprocessable_entity unless status

    issue = Issue.new(
      subject:  params[:subject],
      project_id: list.project_id,
      tracker_id: tracker.id,
      status_id:  status.id,
      author_id:  User.current.id,
      fixed_version_id: list.version_project_id
    )

    if issue.save
      issue.todolist_issues.create!(todo_list_id: list.id)
      render json: { id: issue.id, subject: issue.subject }, status: :ok
    else
      Rails.logger.error "Erreur création issue : #{issue.errors.full_messages.inspect}"
      render json: { error: issue.errors.full_messages.join(", ") }, status: :unprocessable_entity
    end
  end

  def move_issue
    issue = Issue.find(params[:id])
    new_list = TodoList.find(params[:list_id])

    link = TodolistIssue.find_or_initialize_by(issue: issue)
    link.update!(todo_list: new_list)

    if issue.fixed_version_id != new_list.version_project_id
      issue.update!(fixed_version_id: new_list.version_project_id)
    end

    reorder_issues(new_list, params[:ordered_ids])

    render json: { status: 'ok' }
  end

  def reorder_list
    list = TodoList.find(params[:id])
    reorder_issues(list, params[:ordered_ids])
    render json: { status: 'ok' }
  end

  def synchronize
    synchronize_todo_lists_with_project_versions
    respond_to do |format|
      format.html { redirect_to my_space_todo_index_path }
      format.js
    end
  end

  def configuration_required
  end

  private

  #######################################################################
  #   CRÉATION DU PROJET PERSONNEL (corrigée & atomique)
  #######################################################################
  def find_project
    config = Setting.plugin_redmine_asap_user_features

    parent_id  = config['settings_menu_todo_project_parent']
    tracker_id = config['settings_menu_todo_tracker']

    if parent_id.blank? || tracker_id.blank?
      redirect_to controller: 'todo', action: 'configuration_required'
      return
    end

    project_identifier = "user-#{User.current.id}"
    created = false

    @user_project = Project.find_or_create_by!(identifier: project_identifier) do |p|
      created = true
      p.name      = l(:label_list_personal_project) + User.current.to_s
      p.parent_id = parent_id.to_i
      p.is_public = false
    end

    if created
      tracker = Tracker.find(tracker_id.to_i)
      @user_project.trackers = [tracker]

      @user_project.disable_module!(:easy_gantt)
      @user_project.disable_module!(:easy_baselines)
      @user_project.disable_module!(:news)
      @user_project.disable_module!(:time_tracking)

      @user_project.add_default_member(User.current)

      default_version = @user_project.versions.create!(name: l(:label_list_default))
      @user_project.update(default_version: default_version)
    end

    @user_project
  end

  #######################################################################
  #   SYNCHRONISATION VERSIONS ↔ TODO LISTS (corrigée)
  #######################################################################
  def synchronize_todo_lists_with_project_versions
    existing_version_ids = @user_project.versions.pluck(:id)

    # Retire les listes liées à des versions supprimées
    TodoList.where(project_id: @user_project.id, type_list: 'list')
            .where.not(version_project_id: existing_version_ids)
            .destroy_all

    versions   = @user_project.versions.to_a
    todo_lists = TodoList.where(project_id: @user_project.id, type_list: 'list').to_a

    versions.each do |version|
      list = todo_lists.find { |l| l.version_project_id == version.id }

      if list.nil?
        TodoList.create!(
          name: version.name,
          project_id: @user_project.id,
          version_project_id: version.id,
          type_list: 'list'
        )
      elsif list.name != version.name
        list.update!(name: version.name)
      end
    end

    # Cas initial où aucune version n'existe → création
    if versions.empty? && todo_lists.empty?
      version = @user_project.versions.create!(name: 'Liste par défaut')
      TodoList.create!(
        name: version.name,
        project_id: @user_project.id,
        version_project_id: version.id,
        type_list: 'list'
      )
    end

    # IMPORTANT : retourner la liste finale !
    TodoList.where(project_id: @user_project.id, type_list: 'list')
            .order(positionlist: :asc)
  end

  #######################################################################
  #   UTILS
  #######################################################################

  def reorder_issues(list, ordered_ids)
    return unless ordered_ids.present?

    ordered_ids.each_with_index do |id, index|
      ti = TodolistIssue.find_by(issue_id: id, todo_list_id: list.id)
      ti.update!(position: index + 1) if ti
    end
  end

  def find_todo_list
    @todo_list = TodoList.where(project_id: @user_project.id).first
  end

  def get_only_opened_issues_from_todo_lists(todo_lists)
    Array(todo_lists).each do |todo_list|
      todo_list.issues = Array(todo_list.issues).reject(&:closed?)
    end
    todo_lists
  end
end

app/views/todo/index.html.erb
<div class="flex h-[calc(100vh-6rem)]  overflow-auto">
  <%= render "shared/sidebar" %>


  <div data-controller="todo" data-todo-newlist-value="<%= new_my_space_todo_list_path(project_id: @user_project.id) %>" class="flex flex-col flex-1 h-full pl-20 pr-8 w-full">
    <div class="flex flex-col md:flex-row items-center  mt-8 mb-2 px-4 md:px-0">
      <div class="ml-auto flex items-center justify-end w-36">
        <%= link_to synchronize_my_space_todo_index_path,
            method: :post,
            data: { turbo_confirm: 'Synchroniser les listes de tâches avec les versions du projet ?' },
            class: 'p-2 rounded-full hover:bg-gray-100 text-gray-700 dark:text-gray-300 dark:hover:text-gray-300 dark:hover:bg-gray-700 hover:text-gray-800' do %>
            <%= sprite_icon('reload', plugin: 'redmine_asap_user_features', size: 20, css_class: 'stroke-gray-800!') %>
            <% end %>
        <button
            data-action="click->todo#newList"
            class="cursor-pointer bg-blue-700 rounded-full hover:bg-blue-800 p-2 ml-2">
          <%= sprite_icon('plus', plugin: 'redmine_asap_user_features', size: 20, css_class: 'stroke-blue-100!') %>
        </button>

      </div>
    </div>
    <div class="flex flex-col  md:flex-row px-0 mt-0 mb-0 h-[calc(100vh-160px)] w-full overflow-x-auto">
      <% @todo_lists.each do |list| %>
        <div class="flex h-full md:overflow-hidden w-full md:w-64 mr-4 mb-4 md:mb-0 flex-col flex-shrink-0 bg-gray-100 dark:bg-gray-800 rounded-lg py-4 px-4 md:p-4">
          <div class="group flex items-center w-full">
            <h1 class="py-2.5! flex items-center justify-center mb-0! uppercase font-extralight text-xs">
              <%= list.name %>
            </h1>
            <div class="ml-auto relative">
              <div data-action="click->todo#showAdminList"
                   class="opacity-0 group-hover:opacity-100 cursor-pointer p-2 rounded-full hover:bg-gray-200 text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:bg-gray-700 hover:text-gray-800">
                <%= sprite_icon('dots-vertical', plugin: 'redmine_asap_user_features', size: 20, css_class: 'stroke-gray-800!') %>
              </div>
              <div class="absolute right-0 shadow rounded border border-gray-50 mt-0 bg-white z-49 w-44 top-8 hidden" data-todo-target="listmenu">
                <div class="px-4 py-2.5 inline-flex hover:bg-gray-50 cursor-pointer w-full"
                  data-action="click->todo#updateList"
                  data-url="<%= edit_my_space_todo_list_path(id: list.id, project_id: @user_project.id) %>">
                  <%= sprite_icon('edit', size: 18, css_class: 'stroke-gray-800! mr-2') %>
                  <%= l(:label_list_edit) %>
                </div>
                <%= link_to my_space_todo_list_path(list), method: :delete, class: 'px-4 py-2.5 w-full inline-flex hover:bg-gray-50 cursor-pointer text-gray-900!', data: {confirm: t("label_list_delete_confirm", name: list.name)} do %>
                  <%= sprite_icon('del', size: 18, css_class: 'stroke-gray-800! mr-2') %>
                  <%= l(:label_list_delete) %>
                <% end %>
              </div>
            </div>

          </div>
          <div  id="column-issues"
                class="overflow-auto"
                data-controller="sortable"
                data-sortable-list-id-value="<%= list.id %>">
            <% list.issues.each do |issue| %>
            <div
                data-todo-target="issue"
                data-issue-id="<%= issue.id %>"
                class="bg-white mt-3 rounded flex shadow dark:bg-gray-700 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
              >
                <div class="flex items-center justify-center px-4 py-4">
                  <input
                    type="checkbox"
                    class=""
                    data-action="change->todo#completeIssue"
                    data-issue-id="<%= issue.id %>"
                    <%= 'checked' if issue.closed? %>
                  >
                </div>
                <div class="font-normal text-xs w-full text-gray-900 dark:text-gray-100 nowrap ">
                  <%= link_to issue.subject, issue_path(issue), class: 'pr-4 py-4 flex items-center text-gray-900! dark:text-gray-100!' %>
                </div>
              </div>
            <% end %>
          </div>

          <div data-controller="todo-add" data-todo-add-list-id-value="<%= list.id %>" class="mt-4">
            <button
              type="button"
              class="px-2 py-1 font-light cursor-pointer"
              data-action="click->todo-add#showForm"
              data-todo-add-target="plusButton"
              >
              <%= l(:label_todo_add) %>
            </button>
            <form
              data-action="submit->todo-add#addIssue"
              class="hidden! flex items-center mt-2"
              data-todo-add-target="form"
            >
              <input type="text"
                    class="border border-white bg-white! p-4 rounded"
                    placeholder="<%= l(:label_todo_new) %>"
                    data-todo-add-target="input" />
                  <div class="mt-4">
              <button type="submit" class="ml-2 bg-blue-500! hover:bg-blue-600 px-3 py-1 mb-2 rounded text-white"><%= l(:label_todo_create) %></button>
              <button
                type="button"
                class="ml-1 px-2 py-1 cursor-pointer"
                data-action="click->todo-add#cancelForm"
                ><%= l(:label_todo_cancel) %></button>
              </div>
            </form>
          </div>
        </div>
      <% end %>
    </div>
    <div data-todo-target="app"></div>

    </div>
  </div>



</div>